{% set version = "0.2" %}

package:
  name: umalqurra
  version: {{ version }}

source:
  fn: umalqurra-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/u/umalqurra/umalqurra-{{ version }}.tar.gz
  sha256: 719f6a36f908ada1c29dae0d934dd0f1e1f6e3305784edbec23ad719397de678

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - umalqurra

about:
  home: https://github.com/tytkal/python-hijiri-ummalqura
  license: Waqef
  summary: 'Date Api that support Hijri Umalqurra calendar.'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
