travis:
  secure:
    BINSTAR_TOKEN: X6bfam85vgwxb12076nh1++p4GvRxw47vbQtzHpmdZLg5Au0EfQCx/yMllmDCYYh+Pp3Fc2wKXml73lfdKjm5fUccsbxsRjjyRxG8wTHDqCg66S4r7z1X7nkSlqzFDD3La+bFbXifqmvC5IdFiNnFqANIQ5Sjdmpzu1ga+lJV0KhhOJzzbj6jkNLilkclc5ge5FiQfKRpPY2hdd6mD3ruCWOmLKFsAP66yFK1OuaLSdtQtsa45/xVxeQfQWlqMviQeZ1jK0GHBgGzU9VgyLqTHAYG7kKdCG6wmBxEfFmdY9fYYw4dzXcn090CnOTzNLAJnlGPNyHZFpAWXSaCESbwEoqTLGy8QxUEShZro9A9LCx9WdENgjXUNKmMUhaSvYzrxl945NL19DsB2naPwfrM+gQiMEK40t+ieM+13B794ruGCRn90kLjMCsJmyUDOi1fizBv9FfX0I/zgyn2NC6pA0dpzLjesf46v7EMVWnZ+YhVvx39nvhne/npwNJi+AZmaIl0Mu172fNX10SmZ93ATLudiYQ6bUV7Il+yzsyrB6F9e0MZpHvtt3pJnwY8yjcpOPFGjl37bNLyQhAarQGLJsyMjJSzD708UzaIMRbmIbknQmopDii4HmOVZ+7wmw39jiNxGcPA2vo57Xr1s45DSBpZ2Ilx0OOVTuHF+lUeHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
