travis:
  secure:
    BINSTAR_TOKEN: fbHb3hWlAJfziusFtj0/qccwQRrR41V6i0uYQ5f7iPl5qkAcsL8dTj6840HcgyhvmtZsd0CxxMn/YeK9HZK684RE569rG6bcIuijEFq4W34TFN8rmyV2aW2HkymIDD8IHrKh6mzTSUzAgvkmmO8jVzt4ZCaiqbk1+tOtmCDD16KiZcrVU8w1KNEOmerGY80AqsA4Ib8WJxqf9CR9KFItl+iXTxJssyj7f8YK+SUPHXU3KGKT4RK2b3+93GcuLIiz/EoEdbljrd3vze7eNF2v8+mdcXED7ZqggVUyLEG5tnJDArGo3ADZX5lrWJQwvB8sI28s+3OLcwrXk71x+6McPW3uWUatzlcLsjQe2JJIlZYA07aoUBJ4u89nsbQTxFvR1dKvXAeMjeSeVIIQ/EwT6LP8i+vbprnzdKd3rZh7R5GzuhinyEokW3XNijuLtOqWN4MHbx52+MHl8g2d+70HCmO4xJepmdKYYHaVaUp8UYyJuOzOtgpOiCHsuqxaQt3VQUJMgrkQ65dr8yVrlRMVCZl/QcSuIRFNpdkST8KTWCVwfCEpGpfnk4L1CE7OOnUtzYVJ7l4WSTaYwprEPPvYBkzI4RgOmvCW5oENp252y4v5tyhQNZEtj5JIOnt4FqwTyR0dvKQ2ueUwDYhIRGwHcTPQR/EkfbN1DM6xv5X8n9o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
